Added shellcheck

diff --git a/bash/bash_functions b/bash/bash_functions
--- a/bash/bash_functions
+++ b/bash/bash_functions
@@ -1,24 +1,5 @@
-#
-# path_add <path> [direction] [varname]
-#
-# path_add takes a directory name, an optional direction name (defaults to
-# "after" to append to list) and an optional variable name (defaults to PATH)
-# and adds the directory name to data stored in variable.
-#
-# Example
-#
-# given: PATH='/bin:/sbin'
-#
-# path_add /usr/bin
-# // PATH => '/bin:/sbin:/usr/bin'
-# path_add /opt/local/bin before
-# // PATH => '/opt/local/bin:/bin:/sbin:/usr/bin'
-#
-# The variable name should be passed by name.
-# foo=''
-# path_add /bin after foo
-# // foo => '/bin'
-#
+#!/usr/bin/env bash
+
 path_add() {
 	local var=${3:-PATH}
 	local path=
@@ -26,27 +7,6 @@ path_add() {
 	read -r "${var?}" <<< "$path"
 }
 
-#
-# path_remove <path> [varname]
-#
-# path_remove takes a directory name and an optional variable name (defaults to
-# PATH) and removes every instance of the directory name from the data stored in
-# the variable.
-#
-# Example
-#
-# given: PATH='/bin:/sbin:/usr/bin:/usr/sbin'
-#
-# path_remove /usr/bin
-# // PATH => '/bin:/sbin:/usr/sbin'
-# path_remove /not-found
-# // PATH => '/bin:/sbin:/usr/sbin'
-#
-# The variable name should be passed by name.
-# foo='/bin:/sbin'
-# path_remove /bin foo
-# // foo => '/sbin'
-#
 path_remove() {
 	local var=${2:-PATH}
 	local path=
@@ -54,32 +14,6 @@ path_remove() {
 	read -r "${var?}" <<< "$path"
 }
 
-#
-# path_clean [varname]
-#
-# path_clean takes an optional variable name (defaults to PATH) and "cleans" it,
-# this process will:
-#
-# 1. Remove empty elements.
-# 2. Remove relative directories.
-# 3. Remove directories that don't exist/can't be accessed (checked with `cd`).
-# 4. Remove duplicates (first element stays, subsequent elements are tossed).
-#
-# Example
-#
-# PATH='::/bin:/sbin:::./:../../some-path::/doesnt-exist'
-# path_clean
-# // PATH => '/bin:/sbin'
-
-# PATH='/bin:/bin//:////bin//////:/bin/dir/..::'
-# path_clean
-# // PATH => '/bin'
-#
-# The variable name should be passed by name.
-# foo='/bin:/bin'
-# path_clean /bin foo
-# // foo => '/bin'
-#
 path_clean() {
 	local var=${1:-PATH}
 	local path=
@@ -87,10 +21,6 @@ path_clean() {
 	read -r "${var?}" <<< "$path"
 }
 
-#
-# Exact same usage as path_add but prints the new PATH only and doesn't modify
-# anything in place.
-#
 path_print_add() {
 	local p=$1
 	local dir=${2:-after}
@@ -114,10 +44,6 @@ path_print_add() {
 	echo "${arr[*]}"
 }
 
-#
-# Exact same usage as path_remove but prints the new PATH only and doesn't
-# modify anything in place.
-#
 path_print_remove() {
 	local p=$1
 	local var=${2:-PATH}
@@ -144,10 +70,6 @@ path_print_remove() {
 	echo "${newarr[*]}"
 }
 
-#
-# Exact same usage as path_clean but prints the new PATH only and doesn't
-# modify anything in place.
-#
 path_print_clean() {
 	local var=${1:-PATH}
 	local arr
@@ -204,28 +126,35 @@ gmb() { # git main branch
 
 # show the diff from inside a branch to the main branch
 gbd() { # git branch diff
-	local mb=$(gmb) || return 1
+	local mb
+	mb=$(gmb) || return 1
 	git diff "$mb..HEAD"
 }
 
 # checkout the main branch and update it
 gcm() { # git checkout $main
-	local mb=$(gmb) || return 1
+	local mb
+	mb=$(gmb) || return 1
 	git checkout "$mb" && git pull
 }
 
 # merge the main branch into our branch
 gmm() { # git merge $main
-	local mb=$(gmb) || return 1
+	local mb
+	mb=$(gmb) || return 1
 	git merge "$mb"
 }
 
 # print a colorized diff
 colordiff() {
-	local red=$(tput setaf 1 2>/dev/null)
-	local green=$(tput setaf 2 2>/dev/null)
-	local cyan=$(tput setaf 6 2>/dev/null)
-	local reset=$(tput sgr0 2>/dev/null)
+	local red
+	red=$(tput setaf 1 2>/dev/null)
+	local green
+	green=$(tput setaf 2 2>/dev/null)
+	local cyan
+	cyan=$(tput setaf 6 2>/dev/null)
+	local reset
+	reset=$(tput sgr0 2>/dev/null)
 
 	diff -u "$@" | awk "
 	/^\-/ {
@@ -274,9 +203,12 @@ gho() {
 	local remote=${2:-origin}
 
 	# get the git root dir, branch, and remote URL
-	local gr=$(git rev-parse --show-toplevel)
-	local branch=$(git rev-parse --abbrev-ref HEAD)
-	local url=$(git config --get "remote.$remote.url")
+	local gr
+	gr=$(git rev-parse --show-toplevel)
+	local branch
+	branch=$(git rev-parse --abbrev-ref HEAD)
+	local url
+	url=$(git config --get "remote.$remote.url")
 
 	[[ -n $gr && -n $branch && -n $remote ]] || return 1
 
@@ -386,6 +318,7 @@ set_prompt_colors() {
 			COLOR256[$i]=$(tput setaf "$i")
 			color=${COLOR256[$i]}
 		fi
+		# shellcheck disable=SC2034
 		PROMPT_COLORS[$j]=$color
 		((j++))
 	done
@@ -398,4 +331,129 @@ _prompt_command() {
 	local ssh=
 	[[ -n $SSH_CLIENT ]] && ssh='[ssh] '
 	printf "\033]0;%s%s@%s:%s\007" "$ssh" "$user" "$host" "$pwd"
+}
+
+# Create a new directory and enter it
+function mkd() {
+	mkdir -p "$@" && cd "$_" || exit;
+}
+
+# Create a .tar.gz archive, using `zopfli`, `pigz` or `gzip` for compression
+function targz() {
+	local tmpFile
+	# shellcheck disable=SC2124
+	tmpFile="${@%/}.tar";
+	tar -cvf "${tmpFile}" --exclude=".DS_Store" "${@}" || return 1;
+
+	size=$(
+		stat -f"%z" "${tmpFile}" 2> /dev/null; # macOS `stat`
+		stat -c"%s" "${tmpFile}" 2> /dev/null;  # GNU `stat`
+	);
+
+	local cmd="";
+	if (( size < 52428800 )) && hash zopfli 2> /dev/null; then
+		# the .tar file is smaller than 50 MB and Zopfli is available; use it
+		cmd="zopfli";
+	else
+		if hash pigz 2> /dev/null; then
+			cmd="pigz";
+		else
+			cmd="gzip";
+		fi;
+	fi;
+
+	echo "Compressing .tar ($((size / 1000)) kB) using \`${cmd}\`…";
+	"${cmd}" -v "${tmpFile}" || return 1;
+	[ -f "${tmpFile}" ] && rm "${tmpFile}";
+
+	zippedSize=$(
+		stat -f"%z" "${tmpFile}.gz" 2> /dev/null; # macOS `stat`
+		stat -c"%s" "${tmpFile}.gz" 2> /dev/null; # GNU `stat`
+	);
+
+	echo "${tmpFile}.gz ($((zippedSize / 1000)) kB) created successfully.";
+}
+
+# Determine size of a file or total size of a directory
+function fs() {
+	if du -b /dev/null > /dev/null 2>&1; then
+		local arg=-sbh;
+	else
+		local arg=-sh;
+	fi
+	# shellcheck disable=SC2199
+	if [[ -n "$@" ]]; then
+		du $arg -- "$@";
+	else
+		du $arg .[^.]* ./*;
+	fi;
+}
+
+function server() {
+	local port="${1:-8000}";
+	sleep 1 && open "http://localhost:${port}/" &
+	# Set the default Content-Type to `text/plain` instead of `application/octet-stream`
+	# And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
+	python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port";
+}
+
+# Show all the names (CNs and SANs) listed in the SSL certificate
+# for a given domain
+function getcertnames() {
+	if [ -z "${1}" ]; then
+		echo "ERROR: No domain specified.";
+		return 1;
+	fi;
+
+	local domain="${1}";
+	echo "Testing ${domain}…";
+	echo ""; # newline
+
+	local tmp
+	tmp=$(echo -e "GET / HTTP/1.0\nEOT" \
+		| openssl s_client -connect "${domain}:443" -servername "${domain}" 2>&1);
+
+	if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
+		local certText
+		certText=$(echo "${tmp}" \
+			| openssl x509 -text -certopt "no_aux, no_header, no_issuer, no_pubkey, \
+			no_serial, no_sigdump, no_signame, no_validity, no_version");
+		echo "Common Name:";
+		echo ""; # newline
+		echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//" | sed -e "s/\/emailAddress=.*//";
+		echo ""; # newline
+		echo "Subject Alternative Name(s):";
+		echo ""; # newline
+		echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
+			| sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2;
+		return 0;
+	else
+		echo "ERROR: Certificate not found.";
+		return 1;
+	fi;
+}
+
+function tre() {
+	tree -aC -I '.git|node_modules|bower_components' --dirsfirst "$@" | less -FRNX;
+}
+
+# Normalize `open` across Linux, macOS, and Windows.
+# This is needed to make the `o` function (see below) cross-platform.
+if [ ! "$(uname -s)" = 'Darwin' ]; then
+	if grep -q Microsoft /proc/version; then
+		# Ubuntu on Windows using the Linux subsystem
+		alias open='explorer.exe';
+	else
+		alias open='xdg-open';
+	fi
+fi
+
+# `o` with no arguments opens the current directory, otherwise opens the given
+# location
+function o() {
+	if [ $# -eq 0 ]; then
+		open .;
+	else
+		open "$@";
+	fi;
 }
diff --git a/install b/install
--- a/install
+++ b/install
@@ -47,7 +47,8 @@ spinner() {
 
 center_text() {
 	local text="$1"
-	local term_width=$(tput cols 2>/dev/null || echo 80)
+	local term_width
+  term_width=$(tput cols 2>/dev/null || echo 80)
 	local text_len=${#text}
 	local pad=$(( (term_width - text_len) / 2 ))
 	printf "%*s%s" "$pad" "" "$text"
@@ -83,6 +84,68 @@ install_pkg() {
   fi
 
   sudo apt-get install -qq -y "$pkg" >/dev/null 2>&1 &
+  local pid=$!
+
+  spinner "$pid" "$msg"
+
+  local status
+  if wait "$pid"; then status=0; else status=$?; fi  # <-- works with set -e
+
+  if [[ $status -eq 0 ]]; then
+    printf '\r%55s %bDONE%b' "$msg" "$GREEN" "$NC"
+  else
+    printf '\r%55s %bFAIL%b' "$msg" "$RED" "$NC"
+  fi
+  tput el 2>/dev/null || printf '      '
+  printf '\n'
+
+  return "$status"
+}
+
+ensure_locale() {
+  local msg="Ensuring en_US.UTF-8 locale exists"
+
+  if [[ $SUDO_REFRESHED -eq 0 ]]; then
+    if ! sudo -n true 2>/dev/null; then
+      printf '\n%s\n' "sudo access required to install packages."
+      sudo -v
+    fi
+    SUDO_REFRESHED=1
+  fi
+
+  sudo locale-gen en_US.UTF-8 >/dev/null 2>&1 &
+  local pid=$!
+
+  spinner "$pid" "$msg"
+
+  local status
+  if wait "$pid"; then status=0; else status=$?; fi  # <-- works with set -e
+
+  if [[ $status -eq 0 ]]; then
+    printf '\r%55s %bDONE%b' "$msg" "$GREEN" "$NC"
+  else
+    printf '\r%55s %bFAIL%b' "$msg" "$RED" "$NC"
+  fi
+  tput el 2>/dev/null || printf '      '
+  printf '\n'
+
+  return "$status"
+}
+
+run_command() {
+	local msg=${1:?msg arg required}
+	shift
+	# local cmd=${2:?cmd arg required}
+
+  if [[ $SUDO_REFRESHED -eq 0 ]]; then
+    if ! sudo -n true 2>/dev/null; then
+      printf '\n%s\n' "sudo access required to install packages."
+      sudo -v
+    fi
+    SUDO_REFRESHED=1
+  fi
+
+  "$@" >/dev/null 2>&1 &
   local pid=$!
 
   spinner "$pid" "$msg"
@@ -164,9 +227,15 @@ else
 fi
 
 echo
+run_command "Ensuring en_US.UTF-8 locale exists" sudo locale-gen en_US.UTF-8
+run_command "Updating en_US.UTF-8 locale" sudo update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
+echo
+
+echo
 handle_pkg_install
 echo
 
 echo
 echo -e "\033[0;32mDOTFILES INSTALLED SUCCESSFULLY. CAN TEST EXTRA BINS WITH 'ryan_test'\033[0m"
-echo -e "\t - Restart terminal or run 'source ~/.bashrc' to get changes\n"
+echo -e "\t - Restart terminal or run 'source ~/.bashrc' to get changes"
+echo -e "\t - Run 'install-optional' to install optional packages\n"
